version: '3.8'

services:
  # Base de Datos Relacional para Desarrollo
  postgres-db:
    image: postgres:15-alpine
    container_name: logistics-postgres
    environment:
      POSTGRES_USER: logistics_user
      POSTGRES_PASSWORD: logistics_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # <-- Crucial para crear las 3 DBs
    networks:
      - logistics-network

  # Caché para Desarrollo
  redis-cache:
    image: redis:7-alpine
    container_name: logistics-redis
    ports:
      - "6379:6379"
    networks:
      - logistics-network

  # Message Broker para Desarrollo
  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: logistics-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - logistics-network

  # API Gateway configurado para redirigir el tráfico a tu máquina local
  api-gateway:
    image: nginx:alpine
    container_name: logistics-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuración de Desarrollo
    depends_on:
      - postgres-db
      - rabbitmq-broker
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite a NGINX ver tu máquina local si usas Linux
    networks:
      - logistics-network

volumes:
  postgres_data:

networks:
  logistics-network:
    driver: bridge